#!/bin/bash

set -e

version=$(curl -s https://versionhistory.googleapis.com/v1/chrome/platforms/linux/channels/stable/versions | jq -r '.versions[0].version')

major_version=$(echo $version | cut -d '.' -f 1)

echo $major_version