name: Chrome Main Version Updater
run-name: Update Chrome Version in the HTTP Header 🚀

on: [push]

jobs:
  Deploy-With-Latest-Chrome-Version:
    runs-on: ubuntu-24.04
    environment: cdk
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get Latest Chrome Version
        id: get-latest-chrome-version
        run: echo "MAJOR_VERSION=$(./scripts/latest-chrome-version-check)" >> "$GITHUB_OUTPUT"
      - name: Install nodejs (maybe v22.x lts)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install npm packages
        run: npm ci
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::211125585858:role/Github_Actions_Restock_Notifier_Role
          aws-region: ap-northeast-2
      - name: Build Lambda Function Handler
        run: cd app && npm run deploy
      - name: Deploy CDK APP
        env:
          EMAIL_ADDRESS: ${{vars.EMAIL_ADDRESS}}
          CHROMIUM_MAJOR_VERSION_FAKE: ${{steps.get-latest-chrome-version.outputs.MAJOR_VERSION}}
        run: cd cdk && npm run deploy
