name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Check-Chrome-Version:
    runs-on: ubuntu-24.04
    outputs:
      major-version: ${{steps.output-step.outputs.major-version}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install nodejs (maybe v22.x lts)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Get Latest Chrome Version
        id: output-step
        run: echo "major-version=$(node scripts/latest-chrome-version-check.js)" >> "$GITHUB_OUTPUT"
  Deploy:
    runs-on: ubuntu-24.04
    needs: Check-Chrome-Version
    environment: cdk
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install nodejs (maybe v22.x lts)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install npm packages
        run: npm ci
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::211125585858:role/Github_Actions_Restock_Notifier_Role
          aws-region: ap-northeast-2
      - name: Build Lambda Function Handler
        run: cd app && npm run deploy
      - name: Deploy CDK APP
        env:
          EMAIL_ADDRESS: ${{vars.EMAIL_ADDRESS}}
          CHROMIUM_MAJOR_VERSION_FAKE: ${{needs.Check-Chrome-Version.outputs.major-version}}
        run: cd cdk && npm run deploy
